'use strict'

var chai = require('chai');
var assert = chai.assert;

var NotesApplication = require('./lib/notesapplication.js');
var Note = require('./lib/notes.js');

describe("Note creation works properly", function() {
    it("assigns id, content and author based on the parameter supplied", 
        function() {
            note = new Note("Hello world", "Fortune");
            assert(note.author == "Fortune");
    })
})


describe("Notes application attributes and methods behaves properly",
    function() {
        it("increments the note list as notes are added", function() {

            notesapp = new NotesApplication("Fortune");
            assert(notesapp.notelist.length == 0);
            notesapp.create("Hello world", "Fortune");
            assert(notesapp.notelist.length == 1);
    })

    it("Ensures that created note is added into the notelist", function(){

        notesapp = new NotesApplication();
        notesapp.create("I love Jesus", "Fortune");
        assert(notesapp.notelist.length == notelist.content);
    })

    it("Ensures that note id is generated by length of note list",
        function(){
           notesapp = new NotesApplication();
           notesapp.create("Hello world", "Fortune")
           assert(notesapp.notelist.length == notelist.id) 
        })

    it("Ensures that all available created notes are listed", 
        function(){
            notesapp = new NotesApplication();
            notesapp.create("Hi there!", "Fortune");
            assert(notesapp.listNotes() == "Note ID: 0" +
                "\n Hi there!" + 
                "\n By Author Fortune");
        
    })

    it("Ensures that a given note id returns the content or a user feedback", 
        function(){
            notesapp = new NotesApplication();
            notesapp.create("Hi there!", "Fortune");
            notesapp.create("Hi people", "Iyke");
            assert(notesapp.get(1) == "Hi people");
            assert(notesapp.get(3) == "no note with such id");
    })

    it("Ensures that a given search string returns the note content or a user feedback", 
        function(){
            notesapp = new NotesApplication();
            notesapp.create("Hi there!", "Fortune");
            assert(notesapp.search("there!") == "Hi there!");
            assert(notesapp.search("We") == "not found");
        })


})