'use strict'

var chai = require('chai');
var assert = chai.assert;

var NotesApplication = require('./lib/notesapplication.js');
var Note = require('./lib/notes.js');

describe("Note creation works properly", function() {
    it("assigns id, content and author", 
        function() {
            note = new Note("Hello world", "Fortune");
            assert(note.author == "Fortune");
    })
})


describe("NotesApplication attributes and methods behaves properly",
    function() {
        it("increments the note list as notes are added", 

            function() {
                notesapp = new NotesApplication("Fortune");
                assert(notesapp.notelist.length == 0);
                notesapp.create("Hello world", "Fortune");
                assert(notesapp.notelist.length == 1);
            })

    it("Ensures that created note is added into the notelist", 
        function(){
            notesapp = new NotesApplication();
            notesapp.create("I love Jesus", "Fortune");
            assert(notesapp.notelist.length == notelist.content);
        })

    it("Ensures note id is generated by length of note list",
        function(){
           notesapp = new NotesApplication();
           notesapp.create("Hello world", "Fortune")
           assert(notesapp.notelist.length == notelist.id) 
        })

    it("Ensures all available created notes are listed", 
        function(){
            notesapp = new NotesApplication();
            notesapp.create("Hi there!", "Fortune");
            assert(notesapp.listNotes() == "Note ID: 0" +
                "\n Hi there!" + 
                "\n By Author Fortune");
        
    })

    it("Ensures a given note id returns the content", 
        function(){
            notesapp = new NotesApplication();
            notesapp.create("Hi there!", "Fortune");
            notesapp.create("Hi people", "Iyke");
            assert(notesapp.get(1) == "Hi people");
    })

    it("Ensures a search string returns the note content", 
        function(){
            notesapp = new NotesApplication();
            notesapp.create("Hi there!", "Fortune");
            assert(notesapp.search("there!") == "Hi there!");
        })

    it("Ensures that a note is deleted", function(){
        notesapp = new NotesApplication();
        notesapp.create("Hi there!", "Fortune");
        assert(notesapp.delete(0) == "note deleted \n\n");
    })


    it("Ensures that a note is edited",
        function(){
            notesapp = new NotesApplication();
            notesapp.create("Hi there!", "Fortune");
            assert(notesapp.edit(0, "I love Jesus") == "I love Jesus");
        })

    it("Ensures that user feedbacks are returned",
        function(){
            notesapp = new NotesApplication();
            notesapp.create("Hi there!", "Fortune")
            assert(notesapp.get(3) == "no note with such id");
            assert(notesapp.search("We") == "not found");
            assert(notesapp.delete(1) == "There's no note with such id");
            assert(notesapp.edit(1, "I love Jesus") == "There's no such note");
        })


})